# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-10-22 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20150925_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
